- name: Command Line Tools
  hosts: workers
  remote_user: {{ ansible_user_workers }}
  roles:
    - { role: elliotweiser.osx-command-line-tools }

- name: Install Homebrew
  hosts: workers
  remote_user: {{ ansible_user_workers }}
  roles:
    - geerlingguy.mac.homebrew

- hosts: workers
  remote_user: {{ ansible_user_workers }}
  tasks:
    - name: Update and upgrade Homebrew packages
      homebrew:
        update_homebrew: true
        upgrade_all: true

- name: Orchard Worker Service
  hosts: workers
  remote_user: {{ ansible_user_workers }}
  roles:
    - role: orchard-worker-service
